### ISSUE TITLE
Mesos/utils/*.py should be upstreamed

### ISSUE THREAD

**Issue by andschwa** [Microsoft/mesos-jenkins#66]
In an effort to fix [MESOS-7658](https://issues.apache.org/jira/browse/MESOS-7658), where names with non-ASCII characters are disallowed due to the use of Python 2 on Windows, I've started porting the Python scripts necessary to run the review bot to be single-source Python 2 and Python 3 compatible. However, after examining the logs for the build of the [review](https://reviews.apache.org/r/66964/), I learned that instead of `verify-reviews.py`, we've started using scripts in this repo (namely `get-review-ids.py`).

We need to move these scripts upstream (as in, back to the Mesos repo) so they can part of the Python 3 port. We'll soon want to switch the Mesos Windows Review Bot to use Python 3 instead of Python 2, and it'd be easiest to just make sure all the Python scripts in use work with Python 3.

@ionutbalutoiu Can you help out with this?

**Comment by andschwa** [comment]
(They don't necessarily have to be upstreamed, but if it makes sense to do so, we should. I'm more concerned with ensuring we can switch the Review Bot to Python 3. That's the real issue at hand here.)

**Comment by ionutbalutoiu** [comment]
Hello, Andy! Alin Balutoiu on our side will help with porting this to python 3. I would say we proceed like this:

- Port the Mesos/utils/*.py scripts from here to Python 3. Thus, the Windows reviewbot already starts using py3.
- Potentially clean them up and submit them upstream.

What do you think ?

**Comment by andschwa** [comment]
Sound great. Thanks @ionutbalutoiu. @alinbalutoiu I used the `futurize` Python conversion script on mine, and wrote a bit about it [here](https://reviews.apache.org/r/66964/).

**Comment by alinbalutoiu** [comment]
@andschwa just to double check, the Python scripts are expected to work on both Python 2 and Python 3 as well right?

**Comment by ionutbalutoiu** [comment]
Quick update: Python 3 support was added to the scripts in this repository as part of this PR: https://github.com/Microsoft/mesos-jenkins/pull/71. We're working on upstream the scripts now.

**Comment by andschwa** [comment]
@alinbalutoiu That was my original plan (for the upstream scripts) to make it go over more easily, but it looks to have been scrapped.

@ionutbalutoiu Armand Grillet went and ported the upstream scripts straight to Pyhon 3 using 2to3, the review is here: https://reviews.apache.org/r/67059/

Perhaps you guys can help test it out? I added you Ionut into the #python3 channel on Slack.

Armand said on there yesterday:

> Let's go directly to Python 3. I've worked on cpplint in Python 3 today, taking a version from GitHub and updating our patch to have something that works, I hope I'll have a review request ready by Friday.
We should ask devs to try the new scripts before making them defaults. I was thinking about putting the scripts in a specific directory (e.g. `support/python3`) until we're done with all of them. Once it'll be done and tested for 1/2 weeks, we could make the switch for good.

**Comment by ionutbalutoiu** [comment]
@andschwa, Thank-you for all the info. We'll test them out.

**Comment by ionutbalutoiu** [comment]
Quick update here: The upstream Python 3 support scripts work. We only use `apply-reviews.py`. Since https://github.com/Microsoft/mesos-jenkins/pull/107 this is used and it working as expected.

The work to upstream `Mesos/utils/*.py` is in progress.

**Comment by andschwa** [comment]
Woo hoo! These are upstream now. Thanks @dragoshsch. @ionutbalutoiu think we can swap the build to using the upstreamed scripts now?

**Comment by ionutbalutoiu** [comment]
@andschwa Yes. A new pull request will come here to use the python scripts from upstream. Closing this issue.
